name: Basic Approach
width: 10000
height: 3000
starting_x_bounds: [10, 300]
starting_y_bounds: [2000, 2900]
starting_theta_bounds: [-0.1, 0.1]
starting_alpha_bounds: [-0.05, 0.05]
starting_vel_bounds: [40, 50]
avg_wind_speed_x_sigma: 20
avg_wind_speed_y_sigma: 10
wind_speed_x_var_sigma: 10
wind_speed_y_var_sigma: 5
num_wind_layers: 10