obs_discretization:
  x: []
  y: []
  theta: []
  vx_air: []
  vy_air: []
action_discretization:
  throttle: [0.33, 0.66]
  pitch: [-0.05, 0, 0.05]
max_num_iterations: 1000
discount_factor: 0.9
learning_rate: 0.9
exploration_rate: 0.1