planet: earth
scene_params: basic_approach
plane: cessna
dt: 0.1
uncertainty_magnitude:
  x: 1
  y: 1
  vx_airspeed: 1
  vy_airspeed: 1
  theta: 1
action_limits:
  throttle:
    min: 0.0
    max: 1.0
  pitch:
    min: -0.1745
    max: 0.1745